### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by NeeluMadan** [SasCezar/PedestrianTrajectoryClustering#1]
Hi,

is it possible to share, how this trajectory dataset looks like? A demo would be really helpful.

Thanks..

**Comment by SasCezar** [comment]
Hi, 

For the formats, the projects support two formats, namely Gorrini_et_al and Zhang_et_al. The code for these is in [this file](https://github.com/SasCezar/PedestrianTrajectoryClustering/blob/master/ptcpy/ptcio/positionsio.py). For an example of the format of Gorrini_et_al, you can check [this file](https://github.com/SasCezar/PedestrianTrajectoryClustering/blob/master/ptcpy/ptcio/tests/data/test_positions.csv).

Hope this helps, let me know if you need more help.

**Comment by SasCezar** [comment]
PS: The "Density" column, is the density of the Voronoi region. Is not actually used in the project.

**Comment by NeeluMadan** [comment]
Thanks a lot!

I'll really appreciate it if you could share the "dataset" (if possible). Thanks again!

**Comment by SasCezar** [comment]
Unfortunately, I can't, I'm not the owner of the data. You should contact the authors of the papers. Let me know if you can't reach the authors of Gorrini et al, I can give you the contact of someone that can help you.

**Comment by NeeluMadan** [comment]
That would be nice. Please share the contact details. Thanks!

**Comment by NeeluMadan** [comment]
Another issue is "gorrini2trajectories' is returning a dictionary instead of a type Trajectories. Could you please help to check if that's correct? This in turn unable to complete the clustering process.

**Comment by SasCezar** [comment]
> That would be nice. Please share the contact details. Thanks!

Write me on email @ cezar.sas@gmail.com

> Another issue is "gorrini2trajectories' is returning a dictionary instead of a type Trajectories. Could you please help to check if that's correct? This in turn unable to complete the clustering process.

I will check it now.

**Comment by SasCezar** [comment]
I pushed a fix. It was due to the change in python version (I think I developed on 2.7). I should have created a requirements.txt.
Just be aware that the computation of the modified hausdorff distance is very expensive, as is not optimized at all. Also, the plots are based on the true point position, that's why the canvas is so large, and the output image is small (then you have to crop it).

**Comment by NeeluMadan** [comment]
Thanks! It works now.
